#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-idna
Version  : 2.8
Release  : 47
URL      : https://files.pythonhosted.org/packages/ad/13/eb56951b6f7950cadb579ca166e448ba77f9d24efc03edd7e55fa57d04b7/idna-2.8.tar.gz
Source0  : https://files.pythonhosted.org/packages/ad/13/eb56951b6f7950cadb579ca166e448ba77f9d24efc03edd7e55fa57d04b7/idna-2.8.tar.gz
Summary  : Internationalized Domain Names in Applications (IDNA)
Group    : Development/Tools
License  : ICU
Requires: deprecated-idna-license = %{version}-%{release}
Requires: deprecated-idna-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : setuptools-legacypython

%description
Internationalized Domain Names in Applications (IDNA)
=====================================================

%package legacypython
Summary: legacypython components for the deprecated-idna package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-idna package.


%package license
Summary: license components for the deprecated-idna package.
Group: Default

%description license
license components for the deprecated-idna package.


%package python
Summary: python components for the deprecated-idna package.
Group: Default

%description python
python components for the deprecated-idna package.


%prep
%setup -q -n idna-2.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554320896
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-idna
cp LICENSE.rst %{buildroot}/usr/share/package-licenses/deprecated-idna/LICENSE.rst
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-idna/LICENSE.rst

%files python
%defattr(-,root,root,-)
